# src/Application/ShopBundle/Resources/config/doctrine/Product.orm.yml
Application\ShopBundle\Entity\Product:
  type: entity
  repositoryClass: Application\ShopBundle\Repository\ProductRepository
  table: product
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 100
    code:
      type: string
      length: 50
    price:
      type: decimal
      scale: 2
    price_promotion:
      type: decimal
      scale: 2
      nullable: true
    amount:
      type: integer
      nullable: true
    description:
      type: string
      length: 255
    description_full:
      type: text
    is_active:
      type: boolean
      nullable: true
      default: 0
    created_at:
      type: datetime
    updated_at:
      type: datetime
      nullable: true
  oneToMany:
    reviews:
      targetEntity: Review
      mappedBy: product
      cascade: [ remove ]
    images:
      targetEntity: Image
      mappedBy: product
      cascade: [ remove ]
    transactions:
      targetEntity: ProductTransaction
      mappedBy: product
      #cascade: [ persist ]
      cascade: [ remove ]
  manyToOne:
    category:
      targetEntity: Category
      inversedBy: products
      #cascade: [ persist ]
      joinColumn:
        name: category_id
        referencedColumnName: id
  manyToMany:
#    categories:
#      targetEntity: Category
#      inversedBy: products
#      #cascade: [ persist ]
#      joinTable:
#        name: product_category
#        joinColumns:
#          product_id:
#            referencedColumnName: id
#        inverseJoinColumns:
#          category_id:
#            referencedColumnName: id
    tags:
      targetEntity: Tag
      inversedBy: products
      #cascade: [ persist ]
      joinTable:
        name: product_tag
        joinColumns:
          product_id:
            referencedColumnName: id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ] 
    preUpdate: [ setUpdatedAtValue ]