security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        login:
            pattern:  ^/dashboard/admin_login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                #check_path: /dashboard/admin_login_check
                #login_path: /dashboard/admin_login
                check_path: application_shop_admin_login_check
                login_path: application_shop_admin_login
            logout:
                #path:   /dashboard/admin_logout
                #target: /dashboard
                path:   application_shop_admin_logout
                target: application_shop_admin_homepage
                #target: application_shop_start #przekierowanie do strony głównej po wylogowaniu
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/dashboard/user, roles: ROLE_ADMIN }
        - { path: ^/dashboard/category, roles: ROLE_ADMIN } #dostęp do "dashboard/category" tylko dla admin
        - { path: ^/dashboard, roles: ROLE_USER } #dostęp do "dashboard" dla wszystkich
        
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
