<?php

namespace Application\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
  public function getWithProducts()
  {
      $query = $this->getEntityManager()->createQuery('SELECT c FROM ApplicationShopBundle:Category c LEFT JOIN c.products p WHERE p.category = c.id');

      return $query->getResult();
  }	
}
