<?php

namespace Application\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	
  public function getProductsFromCategory($category_id = null, $max = null, $offset = null)
  {
      $qb = $this->createQueryBuilder('p');
      
      if($max)
      {
          $qb->setMaxResults($max);
      }
      
      if($offset)
      {
      	$qb->setFirstResult($offset);
      }
 
      if($category_id)
      {
          $qb->andWhere('p.category = :category_id')
             ->setParameter('category_id', $category_id);
      }
    
      $query = $qb->getQuery();
 
      return $query->getResult();
  }
  
  public function countProductsFromCategory($category_id = null)
  {
      $qb = $this->createQueryBuilder('p');
 
      if($category_id)
      {
          $qb->andWhere('p.category = :category_id')
             ->setParameter('category_id', $category_id);
      }
 
      $query = $qb->getQuery();
 
      return count($query->getResult());
  }
	
}
